window.allProducts = [
  {
    id: 1,
    name: "The Essential Hoodie",
    description: "Premium cotton fleece with kangaroo pocket and adjustable drawstring",
    price: "Rs.18,000.00",
    originalPrice: "Rs.30,000.00",
    category: "Men",
    subcategory: "Hoodies",
    image: "images/products/blackhoodie.png",
    url: "men/men-hoodies.html",
    keywords: ["hoodie", "essential", "black", "cotton", "fleece", "men"]
  },
  {
    id: 2,
    name: "The Ocean Wave Hoodie",
    description: "Eco-friendly organic cotton with wave pattern embroidery",
    price: "Rs.25,000.00",
    category: "Men",
    subcategory: "Hoodies",
    image: "images/products/oceanblue.png",
    url: "men/men-hoodies.html",
    keywords: ["hoodie", "ocean", "wave", "blue", "organic", "men"]
  },
  {
    id: 3,
    name: "The Forest Explorer Hoodie",
    description: "Durable cotton blend with moisture-wicking technology",
    price: "Rs.21,000.00",
    originalPrice: "Rs.30,000.00",
    category: "Men",
    subcategory: "Hoodies",
    image: "images/products/forestgreen.png",
    url: "men/men-hoodies.html",
    keywords: ["hoodie", "forest", "explorer", "green", "cotton", "men"]
  },
  {
    id: 4,
    name: "The Burgundy Collection",
    description: "Limited edition premium fleece with embossed logo",
    price: "Rs.32,000.00",
    category: "Men",
    subcategory: "Hoodies",
    image: "images/products/deepred.png",
    url: "men/men-hoodies.html",
    keywords: ["hoodie", "burgundy", "red", "limited", "fleece", "men"]
  },
  {
    id: 5,
    name: "The Classic Comfort",
    description: "Soft heather cotton blend with relaxed fit design",
    price: "Rs.22,500.00",
    originalPrice: "Rs.30,000.00",
    category: "Men",
    subcategory: "Hoodies",
    image: "images/products/heathergrey.png",
    url: "men/men-hoodies.html",
    keywords: ["hoodie", "classic", "comfort", "grey", "heather", "men"]
  },
  {
    id: 6,
    name: "The Navy Essential",
    description: "Versatile navy blue hoodie with modern cut and premium fabric",
    price: "Rs.24,000.00",
    category: "Men",
    subcategory: "Hoodies",
    image: "images/products/navyblue.png",
    url: "men/men-hoodies.html",
    keywords: ["hoodie", "navy", "blue", "essential", "men"]
  },
  {
    id: 7,
    name: "The Classic Leather",
    description: "Genuine leather jacket with premium finish",
    price: "Rs.45,000.00",
    category: "Men",
    subcategory: "Jackets",
    image: "images/products/blackjacket.png",
    url: "men/men-jackets.html",
    keywords: ["jacket", "leather", "classic", "black", "men"]
  },
  {
    id: 8,
    name: "The Vintage Denim",
    description: "Classic denim jacket with distressed finish",
    price: "Rs.28,000.00",
    category: "Men",
    subcategory: "Jackets",
    image: "images/products/bluedenim.png",
    url: "men/men-jackets.html",
    keywords: ["jacket", "denim", "vintage", "blue", "men"]
  },
  {
    id: 9,
    name: "The Luxury Fur",
    description: "Premium fur-lined jacket for cold weather",
    price: "Rs.55,000.00",
    category: "Men",
    subcategory: "Jackets",
    image: "images/products/furbrown.jpg",
    url: "men/men-jackets.html",
    keywords: ["jacket", "fur", "luxury", "winter", "warm", "men"]
  },
  {
    id: 10,
    name: "The Modern Raxine",
    description: "Stylish synthetic leather jacket",
    price: "Rs.32,000.00",
    category: "Men",
    subcategory: "Jackets",
    image: "images/products/brownjacket.png",
    url: "men/men-jackets.html",
    keywords: ["jacket", "raxine", "modern", "brown", "men"]
  },
  {
    id: 11,
    name: "The Bomber Leather",
    description: "Classic bomber style leather jacket",
    price: "Rs.48,000.00",
    category: "Men",
    subcategory: "Jackets",
    image: "images/products/bomberblack.png",
    url: "men/men-jackets.html",
    keywords: ["jacket", "bomber", "leather", "black", "men"]
  },
  {
    id: 12,
    name: "The Distressed Denim",
    description: "Distressed denim jacket with vintage appeal",
    price: "Rs.26,000.00",
    category: "Men",
    subcategory: "Jackets",
    image: "images/products/distressblue.jpg",
    url: "men/men-jackets.html",
    keywords: ["jacket", "denim", "distressed", "blue", "vintage", "men"]
  },
  {
    id: 13,
    name: "Classic Formal",
    description: "Professional formal shirt for business occasions",
    price: "Rs.12,000.00",
    category: "Men",
    subcategory: "Shirts",
    image: "images/products/businesswhite.png",
    url: "men/men-shirts.html",
    keywords: ["shirt", "formal", "classic", "white", "business", "men"]
  },
  {
    id: 14,
    name: "Check Casual",
    description: "Casual checked shirt for everyday wear",
    price: "Rs.9,500.00",
    category: "Men",
    subcategory: "Shirts",
    image: "images/products/checkblue.png",
    url: "men/men-shirts.html",
    keywords: ["shirt", "casual", "check", "checked", "blue", "men"]
  },
  {
    id: 15,
    name: "Premium Polo",
    description: "Premium polo shirt with elegant design",
    price: "Rs.11,000.00",
    category: "Men",
    subcategory: "Shirts",
    image: "images/products/bluepolo.png",
    url: "men/men-shirts.html",
    keywords: ["shirt", "polo", "premium", "blue", "men"]
  },
  {
    id: 16,
    name: "Classic Henley",
    description: "Classic henley style casual shirt",
    price: "Rs.8,500.00",
    category: "Men",
    subcategory: "Shirts",
    image: "images/products/henleyblue.png",
    url: "men/men-shirts.html",
    keywords: ["shirt", "henley", "classic", "casual", "blue", "men"]
  },
  {
    id: 17,
    name: "Business Formal",
    description: "Professional business formal shirt",
    price: "Rs.13,500.00",
    category: "Men",
    subcategory: "Shirts",
    image: "images/products/businessblue.png",
    url: "men/men-shirts.html",
    keywords: ["shirt", "business", "formal", "blue", "professional", "men"]
  },
  {
    id: 18,
    name: "Oxford Casual",
    description: "Oxford style casual shirt",
    price: "Rs.10,500.00",
    category: "Men",
    subcategory: "Shirts",
    image: "images/products/blueshirt.png",
    url: "men/men-shirts.html",
    keywords: ["shirt", "oxford", "casual", "blue", "men"]
  },
  {
    id: 19,
    name: "Athletic Sneakers",
    description: "High-performance athletic sneakers",
    price: "Rs.15,000.00",
    category: "Men",
    subcategory: "Footwear",
    image: "images/products/sneakers.png",
    url: "men/men-footwear.html",
    keywords: ["shoes", "sneakers", "athletic", "sports", "men"]
  },
  {
    id: 20,
    name: "Formal Oxfords",
    description: "Classic formal oxford shoes",
    price: "Rs.18,000.00",
    category: "Men",
    subcategory: "Footwear",
    image: "images/products/oxfords.png",
    url: "men/men-footwear.html",
    keywords: ["shoes", "oxfords", "formal", "dress", "men"]
  },
  {
    id: 21,
    name: "Combat Boots",
    description: "Durable combat style boots",
    price: "Rs.22,000.00",
    category: "Men",
    subcategory: "Footwear",
    image: "images/products/bootsblack.png",
    url: "men/men-footwear.html",
    keywords: ["shoes", "boots", "combat", "black", "men"]
  },
  {
    id: 22,
    name: "Canvas Casual",
    description: "Comfortable canvas casual shoes",
    price: "Rs.8,500.00",
    category: "Men",
    subcategory: "Footwear",
    image: "images/products/canvasnavy.png",
    url: "men/men-footwear.html",
    keywords: ["shoes", "canvas", "casual", "navy", "men"]
  },
  {
    id: 23,
    name: "Designer Loafers",
    description: "Premium designer loafers",
    price: "Rs.25,000.00",
    category: "Men",
    subcategory: "Footwear",
    image: "images/products/loafers.png",
    url: "men/men-footwear.html",
    keywords: ["shoes", "loafers", "designer", "premium", "men"]
  },
  {
    id: 24,
    name: "Sports Trainers",
    description: "Professional sports training shoes",
    price: "Rs.16,500.00",
    category: "Men",
    subcategory: "Footwear",
    image: "images/products/trainers.png",
    url: "men/men-footwear.html",
    keywords: ["shoes", "trainers", "sports", "athletic", "men"]
  },
  {
    id: 25,
    name: "The Essential Hoodie",
    description: "Premium cotton fleece with kangaroo pocket",
    price: "Rs.18,000.00",
    originalPrice: "Rs.30,000.00",
    category: "Women",
    subcategory: "Tops",
    image: "images/products/blackhoodie.png",
    url: "women/women-shirts.html",
    keywords: ["hoodie", "essential", "black", "cotton", "women"]
  },
  {
    id: 26,
    name: "The Ocean Wave Hoodie",
    description: "Eco-friendly organic cotton with wave pattern",
    price: "Rs.25,000.00",
    category: "Women",
    subcategory: "Tops",
    image: "images/products/oceanblue.png",
    url: "women/women-shirts.html",
    keywords: ["hoodie", "ocean", "wave", "blue", "women"]
  },
  {
    id: 27,
    name: "The Forest Explorer Hoodie",
    description: "Durable cotton blend with moisture-wicking",
    price: "Rs.21,000.00",
    originalPrice: "Rs.30,000.00",
    category: "Women",
    subcategory: "Tops",
    image: "images/products/forestgreen.png",
    url: "women/women-shirts.html",
    keywords: ["hoodie", "forest", "explorer", "green", "women"]
  },
  {
    id: 28,
    name: "The Burgundy Collection",
    description: "Limited edition premium fleece",
    price: "Rs.32,000.00",
    category: "Women",
    subcategory: "Tops",
    image: "images/products/deepred.png",
    url: "women/women-shirts.html",
    keywords: ["hoodie", "burgundy", "red", "limited", "women"]
  },
  {
    id: 29,
    name: "The Classic Comfort",
    description: "Soft heather cotton blend with relaxed fit",
    price: "Rs.22,500.00",
    originalPrice: "Rs.30,000.00",
    category: "Women",
    subcategory: "Tops",
    image: "images/products/heathergrey.png",
    url: "women/women-shirts.html",
    keywords: ["hoodie", "classic", "comfort", "grey", "women"]
  },
  {
    id: 30,
    name: "The Navy Essential",
    description: "Versatile navy blue hoodie with modern cut",
    price: "Rs.24,000.00",
    category: "Women",
    subcategory: "Tops",
    image: "images/products/navyblue.png",
    url: "women/women-shirts.html",
    keywords: ["hoodie", "navy", "blue", "essential", "women"]
  },
  {
    id: 31,
    name: "The Classic Leather",
    description: "Genuine leather jacket with premium finish",
    price: "Rs.45,000.00",
    category: "Women",
    subcategory: "Jeans & Trousers",
    image: "images/products/blackjacket.png",
    url: "women/women-jeans&trousers.html",
    keywords: ["jacket", "leather", "classic", "black", "women"]
  },
  {
    id: 32,
    name: "The Vintage Denim",
    description: "Classic denim jacket with distressed finish",
    price: "Rs.28,000.00",
    category: "Women",
    subcategory: "Jeans & Trousers",
    image: "images/products/bluedenim.png",
    url: "women/women-jeans&trousers.html",
    keywords: ["jacket", "denim", "vintage", "blue", "women"]
  },
  {
    id: 33,
    name: "The Luxury Fur",
    description: "Premium fur-lined jacket for cold weather",
    price: "Rs.55,000.00",
    category: "Women",
    subcategory: "Jeans & Trousers",
    image: "images/products/furbrown.jpg",
    url: "women/women-jeans&trousers.html",
    keywords: ["jacket", "fur", "luxury", "winter", "women"]
  },
  {
    id: 34,
    name: "The Modern Raxine",
    description: "Stylish synthetic leather jacket",
    price: "Rs.32,000.00",
    category: "Women",
    subcategory: "Jeans & Trousers",
    image: "images/products/brownjacket.png",
    url: "women/women-jeans&trousers.html",
    keywords: ["jacket", "raxine", "modern", "brown", "women"]
  },
  {
    id: 35,
    name: "The Bomber Leather",
    description: "Classic bomber style leather jacket",
    price: "Rs.48,000.00",
    category: "Women",
    subcategory: "Jeans & Trousers",
    image: "images/products/bomberblack.png",
    url: "women/women-jeans&trousers.html",
    keywords: ["jacket", "bomber", "leather", "black", "women"]
  },
  {
    id: 36,
    name: "The Distressed Denim",
    description: "Distressed denim jacket with vintage appeal",
    price: "Rs.26,000.00",
    category: "Women",
    subcategory: "Jeans & Trousers",
    image: "images/products/distressblue.jpg",
    url: "women/women-jeans&trousers.html",
    keywords: ["jacket", "denim", "distressed", "blue", "women"]
  },
  {
    id: 37,
    name: "Classic Formal",
    description: "Professional formal shirt for business",
    price: "Rs.12,000.00",
    category: "Women",
    subcategory: "Outerwear",
    image: "images/products/businesswhite.png",
    url: "women/women-outerwear.html",
    keywords: ["shirt", "formal", "classic", "white", "women"]
  },
  {
    id: 38,
    name: "Check Casual",
    description: "Casual checked shirt for everyday wear",
    price: "Rs.9,500.00",
    category: "Women",
    subcategory: "Outerwear",
    image: "images/products/checkblue.png",
    url: "women/women-outerwear.html",
    keywords: ["shirt", "casual", "check", "blue", "women"]
  },
  {
    id: 39,
    name: "Premium Polo",
    description: "Premium polo shirt with elegant design",
    price: "Rs.11,000.00",
    category: "Women",
    subcategory: "Outerwear",
    image: "images/products/bluepolo.png",
    url: "women/women-outerwear.html",
    keywords: ["shirt", "polo", "premium", "blue", "women"]
  },
  {
    id: 40,
    name: "Classic Henley",
    description: "Classic henley style casual shirt",
    price: "Rs.8,500.00",
    category: "Women",
    subcategory: "Outerwear",
    image: "images/products/henleyblue.png",
    url: "women/women-outerwear.html",
    keywords: ["shirt", "henley", "classic", "casual", "women"]
  },
  {
    id: 41,
    name: "Business Formal",
    description: "Professional business formal shirt",
    price: "Rs.13,500.00",
    category: "Women",
    subcategory: "Outerwear",
    image: "images/products/businessblue.png",
    url: "women/women-outerwear.html",
    keywords: ["shirt", "business", "formal", "blue", "women"]
  },
  {
    id: 42,
    name: "Oxford Casual",
    description: "Oxford style casual shirt",
    price: "Rs.10,500.00",
    category: "Women",
    subcategory: "Outerwear",
    image: "images/products/blueshirt.png",
    url: "women/women-outerwear.html",
    keywords: ["shirt", "oxford", "casual", "blue", "women"]
  },
  {
    id: 43,
    name: "Athletic Sneakers",
    description: "High-performance athletic sneakers",
    price: "Rs.15,000.00",
    category: "Women",
    subcategory: "Footwear",
    image: "images/products/sneakers.png",
    url: "women/women-footwear.html",
    keywords: ["shoes", "sneakers", "athletic", "sports", "women"]
  },
  {
    id: 44,
    name: "Formal Oxfords",
    description: "Classic formal oxford shoes",
    price: "Rs.18,000.00",
    category: "Women",
    subcategory: "Footwear",
    image: "images/products/oxfords.png",
    url: "women/women-footwear.html",
    keywords: ["shoes", "oxfords", "formal", "dress", "women"]
  },
  {
    id: 45,
    name: "Combat Boots",
    description: "Durable combat style boots",
    price: "Rs.22,000.00",
    category: "Women",
    subcategory: "Footwear",
    image: "images/products/bootsblack.png",
    url: "women/women-footwear.html",
    keywords: ["shoes", "boots", "combat", "black", "women"]
  },
  {
    id: 46,
    name: "Canvas Casual",
    description: "Comfortable canvas casual shoes",
    price: "Rs.8,500.00",
    category: "Women",
    subcategory: "Footwear",
    image: "images/products/canvasnavy.png",
    url: "women/women-footwear.html",
    keywords: ["shoes", "canvas", "casual", "navy", "women"]
  },
  {
    id: 47,
    name: "Designer Loafers",
    description: "Premium designer loafers",
    price: "Rs.25,000.00",
    category: "Women",
    subcategory: "Footwear",
    image: "images/products/loafers.png",
    url: "women/women-footwear.html",
    keywords: ["shoes", "loafers", "designer", "premium", "women"]
  },
  {
    id: 48,
    name: "Sports Trainers",
    description: "Professional sports training shoes",
    price: "Rs.16,500.00",
    category: "Women",
    subcategory: "Footwear",
    image: "images/products/trainers.png",
    url: "women/women-footwear.html",
    keywords: ["shoes", "trainers", "sports", "athletic", "women"]
  },
  {
    id: 49,
    name: "The Classic Junior Tee",
    description: "Comfortable cotton t-shirt for juniors",
    price: "Rs.5,500.00",
    category: "Juniors",
    subcategory: "T-Shirts",
    image: "images/products/tshirt.png",
    url: "juniors/juniors-tshirts.html",
    keywords: ["tshirt", "classic", "junior", "cotton", "kids", "juniors"]
  },
  {
    id: 50,
    name: "Graphic Print Tee",
    description: "Fun graphic print t-shirt",
    price: "Rs.6,000.00",
    category: "Juniors",
    subcategory: "T-Shirts",
    image: "images/products/graphictee.png",
    url: "juniors/juniors-tshirts.html",
    keywords: ["tshirt", "graphic", "print", "fun", "kids", "juniors"]
  },
  {
    id: 51,
    name: "Athletic Sports Tee",
    description: "Performance sports t-shirt",
    price: "Rs.6,500.00",
    category: "Juniors",
    subcategory: "T-Shirts",
    image: "images/products/sportstee.png",
    url: "juniors/juniors-tshirts.html",
    keywords: ["tshirt", "athletic", "sports", "performance", "kids", "juniors"]
  },
  {
    id: 52,
    name: "The Cozy Junior Hoodie",
    description: "Warm and cozy hoodie for kids",
    price: "Rs.12,000.00",
    category: "Juniors",
    subcategory: "Hoodies",
    image: "images/products/juniorhoodie.png",
    url: "juniors/juniors-hoodies.html",
    keywords: ["hoodie", "cozy", "junior", "warm", "kids", "juniors"]
  },
  {
    id: 53,
    name: "Fun Zip Hoodie",
    description: "Zip-up hoodie with fun design",
    price: "Rs.13,500.00",
    category: "Juniors",
    subcategory: "Hoodies",
    image: "images/products/ziphoodie.png",
    url: "juniors/juniors-hoodies.html",
    keywords: ["hoodie", "zip", "fun", "kids", "juniors"]
  },
  {
    id: 54,
    name: "Active Sports Shorts",
    description: "Comfortable sports shorts for active kids",
    price: "Rs.4,500.00",
    category: "Juniors",
    subcategory: "Shorts",
    image: "images/products/shorts.png",
    url: "juniors/juniors-shorts.html",
    keywords: ["shorts", "sports", "active", "kids", "juniors"]
  },
  {
    id: 55,
    name: "Casual Cargo Shorts",
    description: "Casual cargo style shorts",
    price: "Rs.5,000.00",
    category: "Juniors",
    subcategory: "Shorts",
    image: "images/products/cargoshorts.png",
    url: "juniors/juniors-shorts.html",
    keywords: ["shorts", "cargo", "casual", "kids", "juniors"]
  },
  {
    id: 56,
    name: "Junior Sneakers",
    description: "Comfortable sneakers for kids",
    price: "Rs.8,000.00",
    category: "Juniors",
    subcategory: "Sneakers",
    image: "images/products/juniorsneakers.png",
    url: "juniors/juniors-sneakers.html",
    keywords: ["shoes", "sneakers", "junior", "kids", "juniors"]
  },
  {
    id: 57,
    name: "Athletic Running Shoes",
    description: "Performance running shoes for active kids",
    price: "Rs.9,500.00",
    category: "Juniors",
    subcategory: "Sneakers",
    image: "images/products/runningshoes.png",
    url: "juniors/juniors-sneakers.html",
    keywords: ["shoes", "athletic", "running", "sports", "kids", "juniors"]
  }
];
